---
sudo: required
dist: xenial
language: python
# env:
#  - LINT=1
#  - IMAGE="images:debian/buster"
#  - IMAGE="images:debian/stretch"
before_install:
  - sudo apt remove -y --purge lxd lxd-client
  - sudo snap install lxd
  - sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
  - sudo lxd waitready
  - sudo lxd init --auto
  - sudo usermod -a -G lxd travis
  - id
  - sudo su - travis
  - id
install:
  - pip3 install ansible molecule
  - ansible --version
  - molecule --version
script:
  - molecule --debug test
