---
sudo: required
dist: xenial
language: python
env:
 - LINT=1
 - IMAGE="images:debian/buster"
 - IMAGE="images:debian/stretch"
before_install:
  - sudo apt remove -y --purge lxd lxd-client
  - sudo snap install lxd
  - sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
  - sudo lxd waitready
  - sudo lxd init --auto
  - sudo usermod -a -G lxd travis

script:
 - if [ ! -z ${LINT} ]; then echo "Hello, world!"; fi
 - if [ ! -z ${IMAGE} ]; then
      sudo su travis -c 'lxc launch ${IMAGE} mymachinecontainer';
      sudo su travis -c 'lxc exec mymachinecontainer -- sh -c "lsb_release -a || cat /etc/redhat-release || cat /etc/issue"';
   fi
