---
dist: bionic
language: python
python: 3.6

before_install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb
  - vagrant --version
  - sudo vagrant plugin install vagrant-libvirt
install:
  - pip3 install ansible 'molecule[vagrant]'==2.22
  - ansible --version
  - molecule --version
script:
  - sudo vagrant up --provider=libvirt
  - sudo vagrant ssh -c "echo 'hello world!'"
