---
sudo: required
dist: xenial
language: python
python: 3.6
# env:
#  - LINT=1
#  - IMAGE="images:debian/buster"
#  - IMAGE="images:debian/stretch"
install:
  - pip3 install ansible molecule docker
  - ansible --version
  - molecule --version
script:
  - molecule --debug test
