---
- name: Prep system
  include: install_packages.yml

- name: Clone T-Pot repo
  include: clone_tpot_repo.yml

- name: Make Users
  include: make_tpot_user.yml

- name: Setup T-Pot
  include: setup_tpot_config.yml

- name: Setup Directorys and Permissions
  include: setup_directory_files_permissions.yml

- name: Setup grub
  include: setup_grub.yml
  tags: molecule-notest
