---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: instance
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      alias: debian/stretch/amd64
    config:
      security.nesting: 'true'
      security.privileged: 'true'
provisioner:
  name: ansible
  ansible_args:
    - --skip-tags "grub"
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
